#define CONFIGURE_INIT

#include <rtems.h>

#include <inttypes.h>

/* configuration information */

#include <bsp.h> /* for device driver prototypes */

#define CONFIGURE_APPLICATION_NEEDS_CLOCK_DRIVER
#define CONFIGURE_APPLICATION_NEEDS_CONSOLE_DRIVER

#define CONFIGURE_UNIFIED_WORK_AREAS

#define CONFIGURE_UNLIMITED_OBJECTS

/* Configure task stacks and stack checker */
#define CONFIGURE_INIT_TASK_STACK_SIZE 30 * RTEMS_MINIMUM_STACK_SIZE
#define CONFIGURE_STACK_CHECKER_ENABLED

#define CONFIGURE_RTEMS_INIT_TASKS_TABLE

#include <rtems/confdefs.h>

/* end of RTEMS configuration */

#include <stdio.h>

int main(void);

rtems_task
Init(rtems_task_argument /* argument */
)
{
    printf("RTEMS Initialized\n"
           "Starting Rust runtime\n");

    // Call the "main" generated by Rust compiler
    main();

    rtems_task_delete(RTEMS_SELF);
}


